POST http://localhost:8080/1page_with_text?some_key=4f&key2=jfhde&key3=54

###
POST http://localhost:8080/registration?username=pidor&password=der_parol

###
GET http://localhost:8080/registration?username=AAAAAAAAAAAAAAAAAAA&password=AAAAAAAAAAAAAAAAAAAAAAA

###
POST http://localhost:8080/registration

###
GET http://localhost:8080/sort?array=1111&array=22222&array=DJSLWWD
